selenium-hub:
  restart: always
  image: selenium/hub:latest
  ports:
    - "4444:4444"
#selenium-chrome
selenium-chrome:
  restart: always
  image: selenium/node-chrome-debug
  stdin_open: true
  ports:
    - "4577"
  links:
    - selenium-hub:hub
#selenium-firefox
selenium-firefox:
  restart: always
  image: selenium/node-firefox-debug
  stdin_open: true
  ports:
      - "4578"
  links:
    - selenium-hub:hub